// Generated by CoffeeScript 1.3.3

/*
jCaKeDev 1.3
cakedevp.github.com/jcakedev
*/


(function() {
  var Combo, Table, jcakedev,
    __slice = [].slice;

  jcakedev = {
    plugins: {},
    components: [],
    getComponent: function($el) {
      var comp, component, id, _i, _len, _ref;
      id = $el.data("cakeId");
      component = null;
      _ref = this.components;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        comp = _ref[_i];
        if (comp.id === id) {
          component = comp;
          break;
        }
      }
      return component;
    },
    addComponent: function(comp) {
      comp.id = this.newID();
      comp.el.data("cakeId", comp.id);
      return this.components.push(comp);
    },
    removeComponent: function(id) {
      var comp, i, index, _i, _len, _ref;
      index = -1;
      _ref = this.components;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        comp = _ref[i];
        if (comp.id === id) {
          index = i;
          break;
        }
      }
      if (index > -1) {
        return this.components.splice(index, 1);
      }
    },
    newID: function() {
      return Math.random().toString().substring(2);
    },
    init: function($) {
      var plugin, _results;
      _results = [];
      for (plugin in this.plugins) {
        _results.push(this.plugins[plugin].init(this));
      }
      return _results;
    }
  };

  jcakedev.plugins.combo = {
    pluginManager: null,
    init: function(pm) {
      var me;
      this.pluginManager = pm;
      me = this;
      return $.fn.cakeCombo = function() {
        var action, args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (typeof args[0] === "string") {
          action = args[0];
          switch (action) {
            case "getValue":
              return me.getValue(this);
            case "setValue":
              me.setValue(this, args[1]);
              break;
            default:
              console.log("'" + action + "' is not a valid action for cakeCombo");
          }
        } else {
          me.create(this, typeof args[0] === "object" ? args[0] : {});
        }
        return this;
      };
    },
    create: function($elements, params) {
      var defaultValue, delegate, me, options;
      me = this;
      if ((params.options != null) && params.options.length) {
        options = params.options;
        delegate = params.delegate;
        defaultValue = params.defaultValue;
        return $elements.each(function() {
          var combo;
          combo = new Combo($(this), options, delegate);
          if (defaultValue != null) {
            combo.setValue(defaultValue);
          }
          return me.pluginManager.addComponent(combo);
        });
      } else {
        return console.log("No options were defined for cakeCombo");
      }
    },
    getValue: function($obj) {
      var $el, combo, i, values;
      if ($obj.length > 1) {
        return values = (function() {
          var _i, _ref, _results;
          _results = [];
          for (i = _i = 0, _ref = $obj.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
            $el = $obj.eq(i);
            combo = this.pluginManager.getComponent($el);
            if (!(combo != null)) {
              continue;
            }
            _results.push(combo.getValue());
          }
          return _results;
        }).call(this);
      } else {
        combo = this.pluginManager.getComponent($obj);
        if (combo != null) {
          return combo.getValue();
        } else {
          return null;
        }
      }
    },
    setValue: function($obj, value) {
      var $el, combo, i, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = $obj.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        $el = $obj.eq(i);
        combo = this.pluginManager.getComponent($el);
        if (combo != null) {
          _results.push(combo.setValue(value));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  Combo = (function() {

    function Combo(el, options, delegate) {
      var $comboElement, me;
      this.el = el;
      this.options = options;
      this.delegate = delegate;
      this.selectedIndex = 0;
      this.el.addClass("-cakedev-combo");
      $comboElement = $("<table class='-cakedev-combo-element' />");
      $comboElement.append("<tr>" + "<td class='-cakedev-combo-optionText'></td>" + "<td class='-cakedev-combo-arrow'><span class='-cakedev-arrow -cakedev-arrow-down-black'></span></td>" + "</tr>");
      this.el.append($comboElement);
      this.setOptions();
      this.setCurrentOption();
      me = this;
      $comboElement.on("mouseenter", function() {
        me.showList(true);
        return me.setFocus(true);
      });
      $comboElement.on("mouseleave", function(event) {
        var $target;
        $target = event.toElement != null ? $(event.toElement) : $(event.relatedTarget);
        if (!$target.hasClass("-cakedev-combo-list-container") && !$target.closest(".-cakedev-combo-list-container").length) {
          me.hideList(true);
          me.setFocus(false);
        }
        return true;
      });
    }

    Combo.prototype.showList = function(animate) {
      var $el;
      $el = this.el.children(".-cakedev-combo-list-container");
      $el.stop().show();
      if (animate) {
        return $el.animate({
          opacity: 1.0
        }, 200);
      } else {
        return $el.css("opacity", 1.0);
      }
    };

    Combo.prototype.hideList = function(animate) {
      var $el;
      $el = this.el.children(".-cakedev-combo-list-container");
      if (animate) {
        return $el.stop().animate({
          opacity: 0
        }, 200, function() {
          return $el.hide();
        });
      } else {
        $el.stop().hide();
        return $el.css("opacity", 0);
      }
    };

    Combo.prototype.setOptions = function() {
      var $list, $listContainer, me, option, _i, _len, _ref;
      me = this;
      $listContainer = $("<div class='-cakedev-combo-list-container' />");
      $list = $("<ul />");
      _ref = this.options;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        option = _ref[_i];
        $list.append("<li>" + option.text + "</li>");
      }
      $listContainer.append($list);
      $list.children("li").each(function(index) {
        return $(this).on("click", function(event) {
          if (me.selectedIndex !== index) {
            if (typeof me.delegate === "function") {
              me.delegate.call(me.el, me.options[index]);
            }
            me.setValue(me.options[index].value);
            me.setFocus(false);
            me.hideList(false);
            return true;
          }
        });
      });
      $listContainer.on("mouseleave", function(event) {
        var $target;
        $target = event.toElement != null ? $(event.toElement) : $(event.relatedTarget);
        if (!$target.hasClass("-cakedev-combo-element") && !$target.closest(".-cakedev-combo-element").length) {
          me.hideList(true);
          me.setFocus(false);
        }
        return true;
      });
      return this.el.append($listContainer);
    };

    Combo.prototype.setCurrentOption = function() {
      var $options;
      this.el.children("table").find(".-cakedev-combo-optionText").text(this.options[this.selectedIndex].text);
      $options = this.el.children(".-cakedev-combo-list-container").children("ul").children("li");
      $options.removeClass("-cakedev-combo-selectedOption");
      return $options.eq(this.selectedIndex).addClass("-cakedev-combo-selectedOption");
    };

    Combo.prototype.setFocus = function(focus) {
      if (focus) {
        return this.el.children(".-cakedev-combo-element").addClass("-cakedev-combo-focused");
      } else {
        return this.el.children(".-cakedev-combo-element").removeClass("-cakedev-combo-focused");
      }
    };

    Combo.prototype.setValue = function(value) {
      var i, option, _i, _len, _ref;
      if (this.getValue() !== value) {
        _ref = this.options;
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          option = _ref[i];
          if (option.value === value) {
            this.selectedIndex = i;
            break;
          }
        }
        return this.setCurrentOption();
      }
    };

    Combo.prototype.getValue = function() {
      return this.options[this.selectedIndex].value;
    };

    return Combo;

  })();

  jcakedev.plugins.table = {
    pluginManager: null,
    init: function(pm) {
      var me;
      this.pluginManager = pm;
      me = this;
      return $.fn.cakeTable = function() {
        var action, args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        if (typeof args[0] === "string") {
          action = args[0];
          switch (action) {
            case "getSelected":
              console.log("Not implemented yet");
              break;
            case "setData":
              me.setData(this, args[1]);
              break;
            case "setLoading":
              me.setLoading(this);
              break;
            case "removeLoading":
              me.removeLoading(this);
              break;
            default:
              console.log("'" + action + "' is not a valid action for cakeTable");
          }
        } else {
          me.create(this, typeof args[0] === "object" ? args[0] : {});
        }
        return this;
      };
    },
    create: function($elements, params) {
      var data, editable, emptyMessage, erasable, fieldNames, fields, formats, maxRecords, me, selectable;
      me = this;
      fields = params.fields != null ? params.fields : [];
      fieldNames = params.fieldNames != null ? params.fieldNames : {};
      data = params.data != null ? params.data : [];
      maxRecords = params.maxRecords != null ? params.maxRecords : 20;
      formats = params.formats != null ? params.formats : {};
      selectable = params.selectable != null ? params.selectable : false;
      editable = params.editable != null ? params.editable : false;
      erasable = params.erasable != null ? params.erasable : false;
      emptyMessage = params.emptyMessage != null ? params.emptyMessage : "...";
      return $elements.each(function() {
        var table;
        table = new Table($(this), fields, fieldNames, data, maxRecords, formats, selectable, editable, erasable, emptyMessage);
        return me.pluginManager.addComponent(table);
      });
    },
    setData: function($obj, data) {
      var i, table, _i, _ref, _results;
      if (data instanceof Array) {
        _results = [];
        for (i = _i = 0, _ref = $obj.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
          table = this.pluginManager.getComponent($obj.eq(i));
          if (table != null) {
            _results.push(table.setData(data));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    },
    setLoading: function($obj) {
      var i, table, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = $obj.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        table = this.pluginManager.getComponent($obj.eq(i));
        if (table != null) {
          _results.push(table.setLoading());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    },
    removeLoading: function($obj) {
      var i, table, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = $obj.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        table = this.pluginManager.getComponent($obj.eq(i));
        if (table != null) {
          _results.push(table.removeLoading());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    }
  };

  Table = (function() {

    function Table(el, fields, fieldNames, data, maxRecords, formats, selectable, editable, erasable, emptyMessage) {
      var $pages, $records, $wrapper;
      this.el = el;
      this.fields = fields;
      this.fieldNames = fieldNames;
      this.data = data;
      this.maxRecords = maxRecords;
      this.formats = formats;
      this.selectable = selectable;
      this.editable = editable;
      this.erasable = erasable;
      this.emptyMessage = emptyMessage;
      this.loading = false;
      this.currentPage = 0;
      this.el.addClass("-cakedev-table");
      $wrapper = $("<div class='-cakedev-table-wrapper' />");
      $records = $("<table class='-cakedev-table-records' />");
      $pages = $("<div class='-cakedev-table-pages' />");
      $wrapper.append($records);
      $wrapper.append("<div class='-cakedev-table-loading' />");
      $wrapper.append("<div class='-cakedev-table-message'>" + this.emptyMessage + "</div>");
      this.el.append($wrapper);
      this.el.append($pages);
      this.setRecords();
    }

    Table.prototype.setData = function(data) {
      this.data = data;
      this.currentPage = 0;
      if (!this.loading) {
        return this.setRecords();
      }
    };

    Table.prototype.clearData = function() {
      return setData([]);
    };

    Table.prototype.showEmptyMessage = function() {
      return this.el.children(".-cakedev-table-wrapper").children(".-cakedev-table-message").show();
    };

    Table.prototype.hideEmptyMessage = function() {
      return this.el.children(".-cakedev-table-wrapper").children(".-cakedev-table-message").hide();
    };

    Table.prototype.getValueWithFormat = function(field, value) {
      var valueWithFormat;
      if (typeof this.formats[field] === "function") {
        valueWithFormat = this.formats[field].call(value, value);
        if (valueWithFormat != null) {
          value = valueWithFormat;
        }
      }
      if (value != null) {
        return value;
      } else {
        return "";
      }
    };

    Table.prototype.setRecords = function() {
      var $record, $records, end, field, i, start, value, _i, _j, _len, _ref;
      $records = this.el.find(".-cakedev-table-records");
      $records.empty();
      this.setHeaders();
      this.hideEmptyMessage();
      if (this.data.length) {
        start = this.currentPage * this.maxRecords;
        end = start + this.maxRecords;
        for (i = _i = start; start <= end ? _i < end : _i > end; i = start <= end ? ++_i : --_i) {
          if (i >= this.data.length) {
            break;
          }
          $record = $("<tr />");
          $record.append("<td class='-cakedev-table-recordActions' />");
          _ref = this.fields;
          for (_j = 0, _len = _ref.length; _j < _len; _j++) {
            field = _ref[_j];
            value = this.getValueWithFormat(field, this.data[i][field]);
            $record.append("<td>" + value + "</td>");
          }
          $records.append($record);
        }
        if (this.selectable) {
          this.setSelectable();
        }
        if (this.editable) {
          this.setEditable();
        }
        if (this.erasable) {
          this.setErasable();
        }
        $records.find("tr:last td").css("border", "none");
      } else {
        this.showEmptyMessage();
      }
      return this.setPages();
    };

    Table.prototype.setHeaders = function() {
      var $headers, field, fieldName, _i, _len, _ref;
      $headers = $("<tr />");
      $headers.append("<th />");
      _ref = this.fields;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        field = _ref[_i];
        fieldName = this.fieldNames[field] != null ? this.fieldNames[field] : field;
        $headers.append("<th>" + fieldName + "</th>");
      }
      return this.el.find(".-cakedev-table-records").append($headers);
    };

    Table.prototype.setPages = function() {
      var $page, $pages, i, me, pagesCount, _i;
      me = this;
      $pages = this.el.children(".-cakedev-table-pages");
      $pages.empty();
      pagesCount = Math.ceil(this.data.length / this.maxRecords);
      for (i = _i = 0; 0 <= pagesCount ? _i < pagesCount : _i > pagesCount; i = 0 <= pagesCount ? ++_i : --_i) {
        $page = $("<a class='-cakedev-table-page' href='#'>" + (i + 1) + "</a>");
        $page.data("pageIndex", i);
        $page.on("click", function() {
          var index;
          index = $(this).data("pageIndex");
          if (index !== me.currentPage) {
            me.setPage(index);
          }
          return false;
        });
        $pages.append($page);
      }
      $pages.children(".-cakedev-table-page").eq(this.currentPage).addClass("-cakedev-table-currentPage");
      if (this.data.length) {
        this.setNavigationControls();
        return this.setInfo();
      }
    };

    Table.prototype.setNavigationControls = function() {
      var $beginning, $end, $next, $pages, $previous, lastPage, me;
      me = this;
      $pages = this.el.children(".-cakedev-table-pages");
      $previous = $("<a href='#'>&laquo; Anterior</a>");
      $next = $("<a href='#'>Siguiente &raquo;</a>");
      $beginning = $("<a href='#'>Ir al inicio</a>");
      $end = $("<a href='#'>Ir al final</a>");
      lastPage = Math.ceil(this.data.length / this.maxRecords) - 1;
      if (lastPage < 0) {
        lastPage = 0;
      }
      $previous.on("click", function() {
        if (me.currentPage > 0) {
          me.setPage(me.currentPage - 1);
        }
        return false;
      });
      $beginning.on("click", function() {
        me.setPage(0);
        return false;
      });
      $next.on("click", function() {
        if (me.currentPage < lastPage) {
          me.setPage(me.currentPage + 1);
        }
        return false;
      });
      $end.on("click", function() {
        me.setPage(lastPage);
        return false;
      });
      return $pages.prepend($end).prepend($next).prepend($previous).prepend($beginning);
    };

    Table.prototype.setInfo = function() {
      var beginning, end;
      beginning = this.currentPage * this.maxRecords;
      end = beginning + this.maxRecords;
      if (end > this.data.length) {
        end = this.data.length;
      }
      return this.el.children(".-cakedev-table-pages").append("<span class='-cakedev-table-info'>Mostrando " + (beginning + 1) + " a " + end + " de " + this.data.length + "</span>");
    };

    Table.prototype.setPage = function(index) {
      this.currentPage = index;
      return this.setRecords();
    };

    Table.prototype.setSelectable = function() {
      return false;
    };

    Table.prototype.setEditable = function() {
      var $actions, i, _i, _ref, _results;
      $actions = this.el.find(".-cakedev-table-records").find(".-cakedev-table-recordActions");
      _results = [];
      for (i = _i = 0, _ref = $actions.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push($actions.eq(i).append("<span class='-cakedev-table-action -cakedev-edit-icon' />"));
      }
      return _results;
    };

    Table.prototype.setErasable = function() {
      var $actions, i, _i, _ref, _results;
      $actions = this.el.find(".-cakedev-table-records").find(".-cakedev-table-recordActions");
      _results = [];
      for (i = _i = 0, _ref = $actions.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push($actions.eq(i).append("<span class='-cakedev-table-action -cakedev-trash-icon' />"));
      }
      return _results;
    };

    Table.prototype.clearRecords = function() {
      this.el.find(".-cakedev-table-records").find("tr").not(":first").remove();
      this.el.children(".-cakedev-table-pages").empty();
      return this.hideEmptyMessage();
    };

    Table.prototype.setLoading = function() {
      this.clearRecords();
      this.el.children(".-cakedev-table-wrapper").children(".-cakedev-table-loading").show();
      return this.loading = true;
    };

    Table.prototype.removeLoading = function() {
      this.el.children(".-cakedev-table-wrapper").children(".-cakedev-table-loading").hide();
      this.setRecords();
      return this.loading = false;
    };

    return Table;

  })();

  if (typeof jQuery !== "undefined" && jQuery !== null) {
    jcakedev.init(jQuery);
  } else {
    console.log("jQuery not found");
  }

}).call(this);
